### ISSUE TITLE
Problem with displaying a list for selecting a currency in Safari

### ISSUE THREAD

**Issue by vchkhr** [Savolus/react-currency-converter#1]
In Safari on macOS BigSur there is a problem with displaying a list for selecting a currency. Not all the symbols are displaying.
<img width="1549" alt="Screenshot 2020-12-29 at 7 30 11 PM" src="https://user-images.githubusercontent.com/33002390/103302672-d5aed580-4a0c-11eb-8025-e0d064e2dd1e.png">

**Comment by Savolus** [comment]
Fix above issue:
- Add more space for names of countries
